server:
  port: 7999
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_order?serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    river-class-name: com.mysql.cj.jdbc.Driver
###剩下的storage-service-mysql.yml和account-service-mysql.yml和这个配置类似